#!/bin/bash

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
source "$SCRIPT_DIR/_helpers/nice_install.sh"

install_command="sudo pacman -S --needed --noconfirm -- "

install_package "$install_command" "$@"

