#!/bin/sh

# Declare associative array for theme mapping
declare -A theme_map=(
    ["Tokyonight - Night"]="tokyonight-night" 
    ["Tokyonight - Moon"]="tokyonight-moon"
    ["Tokyonight - Storm"]="tokyonight-storm"
    ["Dracula"]="dracula"
    ["Catppuccin - Frappe"]="catppuccin-frappe"
    ["Catppuccin - Latte"]="catppuccin-latte"
    ["Catppuccin - Macchiato"]="catppuccin-macchiato"
    ["Catppuccin - Mocha"]="catppuccin-mocha"
)

# Get user selection
theme=$(gum filter --header="Select a color theme" "${!theme_map[@]}")

# Get the actual theme name
actual_theme="${theme_map[$theme]}"

echo "Setting colorscheme to $theme (${actual_theme})"
wal --theme "$actual_theme"
echo "Done"

# Restart swayosd server to apply the new theme
echo "--------------------------------------------------"
echo "Restarting swayosd-server"
pkill swayosd-server
swayosd-server > /dev/null 2>&1 &
echo "Done"

notify-send -t 5000 "Theme Updated" "Color theme was updated to $theme"
