---
- name: "Check if yay is installed"
  ansible.builtin.command: "which yay"
  register: aur_helper_check
  changed_when: false
  failed_when: false
  become_user: "{{ ansible_user | default(lookup('env', 'USER')) }}"

- name: "Clone and install yay"
  when: aur_helper_check.rc != 0
  block:
    - name: "Install dependencies for building packages"
      become: true
      community.general.pacman:
        name:
          - base-devel
          - git
        state: present
        needed: true # only install if not present

    - name: "Clone yay repo"
      ansible.builtin.git:
        repo: "https://aur.archlinux.org/yay.git"
        dest: "/tmp/yay"
      become_user: "{{ ansible_user | default(lookup('env', 'USER')) }}"

    - name: "Build and install yay"
      ansible.builtin.command:
        cmd: makepkg -si --noconfirm
        chdir: "/tmp/yay"
      become_user: "{{ ansible_user | default(lookup('env', 'USER')) }}"
