#!/usr/bin/env bash
# Theme adapter: starship.
#
# starship can't include files, and palettes must live in the config itself.
# So we render ~/.cache/wal/starship.toml = `palette = "wal"` + the stowed
# ~/.config/starship.toml + a [palettes.wal] table with the main accent.
# .commonshellrc points STARSHIP_CONFIG at it; starship re-reads the config
# on every prompt, so open shells switch on their next prompt.

set -euo pipefail

command -v starship >/dev/null 2>&1 || exit 0   # not installed — nothing to do

base="$HOME/.config/starship.toml"
out="$HOME/.cache/wal/starship.toml"
[ -f "$base" ] || exit 0

tmp="$(mktemp "$out.XXXXXX")"
{
    echo '# Generated by dots theme (adapters/starship.sh) — edit ~/.config/starship.toml'
    echo 'palette = "wal"'
    echo
    cat "$base"
    echo
    echo '[palettes.wal]'
    echo "accent = \"$(cat "$HOME/.cache/wal/accent")\""
} > "$tmp"
mv "$tmp" "$out"
