#!/usr/bin/env bash
# Theme adapter: walker (launcher).
#
# walker's default theme defines its colors as five @define-color lines at the
# top of style.css. We render a "wal" theme (walker config.toml selects it):
# the packaged default style.css with those five lines replaced by wal colors
# + the main accent, generated into the cache and linked into
# ~/.config/walker/themes/wal. Layouts are copied too, so the theme is complete.
# The running walker service is restarted to load it.

set -euo pipefail

command -v walker >/dev/null 2>&1 || exit 0   # not installed — nothing to do

default_theme="/etc/xdg/walker/themes/default"
[ -d "$default_theme" ] || exit 0

theme_dir="$HOME/.cache/wal/walker-theme"
link="$HOME/.config/walker/themes/wal"
wal_json="$HOME/.cache/wal/colors.json"

mkdir -p "$theme_dir" "$(dirname "$link")"
cp "$default_theme"/*.xml "$theme_dir/"

{
    echo "/* Generated by dots theme (adapters/walker.sh) — do not edit. */"
    echo "@define-color window_bg_color $(jq -r .special.background "$wal_json");"
    echo "@define-color accent_bg_color $(cat "$HOME/.cache/wal/accent");"
    echo "@define-color theme_fg_color $(jq -r .special.foreground "$wal_json");"
    echo "@define-color error_bg_color $(jq -r .colors.color1 "$wal_json");"
    echo "@define-color error_fg_color $(jq -r .special.foreground "$wal_json");"
    grep -v '^@define-color' "$default_theme/style.css"
} > "$theme_dir/style.css"

ln -sfn "$theme_dir" "$link"

# the service only reads the theme at startup — restart it like hyprland's autostart
if pgrep -x walker >/dev/null; then
    pkill -x walker || true
    sleep 0.3
    # launched by hyprland, so it doesn't die with the calling terminal/session
    if hyprctl instances 2>/dev/null | grep -q .; then
        hyprctl repl 'hl.exec_cmd("walker --gapplication-service")' >/dev/null
    else
        setsid -f walker --gapplication-service >/dev/null 2>&1
    fi
fi
