#!/usr/bin/env bash
# Theme adapter: yazi.
#
# yazi's preset theme follows ghostty's (wal) ANSI palette on its own; only the
# main accent needs delivering. yazi can't read ~/.cache/wal/accent, so we
# render a "wal" flavor (theme.toml selects it) into the cache and link it
# into ~/.config/yazi/flavors/. Running yazi instances pick it up on restart.

set -euo pipefail

command -v yazi >/dev/null 2>&1 || exit 0   # not installed — nothing to do

accent="$(cat "$HOME/.cache/wal/accent")"
flavor_dir="$HOME/.cache/wal/yazi-flavor"
link="$HOME/.config/yazi/flavors/wal.yazi"

mkdir -p "$flavor_dir" "$(dirname "$link")"

# fg "black" = wal color0, readable on the accent
cat > "$flavor_dir/flavor.toml" <<EOF
# Generated by dots theme (adapters/yazi.sh) — do not edit.
[indicator]
current = { fg = "black", bg = "$accent", bold = true }
parent  = { fg = "black", bg = "$accent" }
EOF

ln -sfn "$flavor_dir" "$link"
