--- 
arch_packages:
  - brightnessctl
  - btop
  - curl
  - entr
  - fd
  - ffmpeg
  - fzf
  - git 
  - htop
  - imagemagick
  - jq
  - just
  - lsd
  - openssh
  - hyprpolkitagent
  - poppler
  - resvg
  - ripgrep
  - starship
  - stow 
  - tmux
  - unzip
  - yazi
  - zip
  - zoxide

aur_packages:
  - python-pywal16
