#!/usr/bin/env bash
# install: teams (category: apps)
# Runs on 'dots install apps' after the category's packages are installed.
# MUST be idempotent — safe to run again on every install.
#
# Microsoft Teams as a web app, the Omarchy way: a .desktop entry that opens
# teams.microsoft.com in a chromeless vivaldi --app window (vivaldi comes from
# packages/apps/packages.txt). Microsoft dropped the native Linux client in
# 2022 — screen sharing goes through Chromium's PipeWire capture +
# xdg-desktop-portal-hyprland.
# The entry also handles msteams: links (what the "Open Teams app" button on
# a meeting's launcher page fires) via the teams-webapp launcher, which turns
# them back into teams.microsoft.com URLs for the --app window.
# Entry and launcher are rewritten on every run so changes here reach the
# machine.
set -euo pipefail

APPS_DIR="$HOME/.local/share/applications"
ICON_DIR="$APPS_DIR/icons"
ICON="$ICON_DIR/Teams.png"
ICON_URL="https://cdn.jsdelivr.net/gh/homarr-labs/dashboard-icons/png/microsoft-teams.png"
DESKTOP_FILE="$APPS_DIR/teams.desktop"
LAUNCHER="$HOME/.local/bin/teams-webapp"

if ! command -v vivaldi >/dev/null 2>&1; then
    echo "vivaldi not found — is vivaldi in packages/apps/packages.txt?" >&2
    exit 1
fi

mkdir -p "$ICON_DIR" "$(dirname "$LAUNCHER")"

if [ ! -s "$ICON" ]; then
    curl -fsSL -o "$ICON" "$ICON_URL"
fi

cat > "$LAUNCHER" <<'EOF'
#!/usr/bin/env bash
# teams-webapp [msteams:-or-https-url] — generated by dots
# (packages/apps/install/teams/install.sh), do not edit.
# Opens Teams in a vivaldi --app window; msteams:/l/... and
# msteams://teams.microsoft.com/l/... become https://teams.microsoft.com/l/...
url="${1:-https://teams.microsoft.com}"
case "$url" in
    msteams:*)
        path="${url#msteams:}"
        path="${path#//teams.microsoft.com}"
        path="/${path#/}"
        url="https://teams.microsoft.com$path"
        ;;
esac
exec vivaldi --app="$url"
EOF
chmod +x "$LAUNCHER"

cat > "$DESKTOP_FILE" <<EOF
[Desktop Entry]
Version=1.0
Name=Teams
Comment=Microsoft Teams web app
Exec=$LAUNCHER %u
Terminal=false
Type=Application
Icon=$ICON
Categories=Network;InstantMessaging;
MimeType=x-scheme-handler/msteams;
StartupNotify=true
StartupWMClass=vivaldi-teams.microsoft.com__-Default
EOF

xdg-mime default teams.desktop x-scheme-handler/msteams
update-desktop-database "$APPS_DIR" 2>/dev/null || true

echo "teams web app installed: $DESKTOP_FILE"
